"""add chats and messages

Revision ID: 36d90a7fc859
Revises: 8969cdadb2f4
Create Date: 2025-07-18 18:22:01.480558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36d90a7fc859'
down_revision: Union[str, None] = '8969cdadb2f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq__Settings__id'), 'Settings', ['id'])
    op.create_unique_constraint(op.f('uq__Users__id'), 'Users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__Users__id'), 'Users', type_='unique')
    op.drop_constraint(op.f('uq__Settings__id'), 'Settings', type_='unique')
    # ### end Alembic commands ###
