"""Fix chats

Revision ID: 4e14f8d1bdf1
Revises: 36d90a7fc859
Create Date: 2025-07-18 19:42:27.339643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e14f8d1bdf1'
down_revision: Union[str, None] = '36d90a7fc859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('premium', sa.Boolean(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__users')),
    sa.UniqueConstraint('email', name=op.f('uq__users__email')),
    sa.UniqueConstraint('id', name=op.f('uq__users__id'))
    )
    op.create_index(op.f('ix__users__username'), 'users', ['username'], unique=True)
    op.create_table('chats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk__chats__author_id__users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__chats')),
    sa.UniqueConstraint('id', name=op.f('uq__chats__id'))
    )
    op.create_index(op.f('ix__chats__author_id'), 'chats', ['author_id'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk__settings__user_id__users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__settings')),
    sa.UniqueConstraint('id', name=op.f('uq__settings__id'))
    )
    op.create_index(op.f('ix__settings__user_id'), 'settings', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name=op.f('fk__messages__chat_id__chats')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__messages')),
    sa.UniqueConstraint('id', name=op.f('uq__messages__id'))
    )
    op.create_index(op.f('ix__messages__chat_id'), 'messages', ['chat_id'], unique=False)
    op.drop_index('ix__Settings__user_id', table_name='Settings')
    op.drop_table('Settings')
    op.drop_index('ix__Users__username', table_name='Users')
    op.drop_table('Users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('premium', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk__Users'),
    sa.UniqueConstraint('email', name='uq__Users__email'),
    sa.UniqueConstraint('id', name='uq__Users__id'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix__Users__username', 'Users', ['username'], unique=True)
    op.create_table('Settings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], name='fk__Settings__user_id__Users'),
    sa.PrimaryKeyConstraint('id', name='pk__Settings'),
    sa.UniqueConstraint('id', name='uq__Settings__id')
    )
    op.create_index('ix__Settings__user_id', 'Settings', ['user_id'], unique=False)
    op.drop_index(op.f('ix__messages__chat_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix__settings__user_id'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix__chats__author_id'), table_name='chats')
    op.drop_table('chats')
    op.drop_index(op.f('ix__users__username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
