"""Add is_user to message

Revision ID: d04cc67b482b
Revises: fde2f3d2bcf8
Create Date: 2025-07-18 22:45:14.195884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd04cc67b482b'
down_revision: Union[str, None] = 'fde2f3d2bcf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_user', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'is_user')
    # ### end Alembic commands ###
