"""Add is_main to chat

Revision ID: fde2f3d2bcf8
Revises: 4e14f8d1bdf1
Create Date: 2025-07-18 22:09:38.638052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fde2f3d2bcf8'
down_revision: Union[str, None] = '4e14f8d1bdf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('is_main', sa.Boolean(), nullable=True))
    op.create_unique_constraint(op.f('uq__chats__id'), 'chats', ['id'])
    op.create_unique_constraint(op.f('uq__messages__id'), 'messages', ['id'])
    op.create_unique_constraint(op.f('uq__settings__id'), 'settings', ['id'])
    op.create_unique_constraint(op.f('uq__users__id'), 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__users__id'), 'users', type_='unique')
    op.drop_constraint(op.f('uq__settings__id'), 'settings', type_='unique')
    op.drop_constraint(op.f('uq__messages__id'), 'messages', type_='unique')
    op.drop_constraint(op.f('uq__chats__id'), 'chats', type_='unique')
    op.drop_column('chats', 'is_main')
    # ### end Alembic commands ###
